function ysol = TP2_X(t,f,y0,v0,k)
%TP2_X
%    YSOL = TP2_X(T,F,Y0,V0,K)

%    This function was generated by the Symbolic Math Toolbox version 8.1.
%    23-Jun-2018 13:23:19

t2 = sqrt(k);
t3 = t.*t2;
t4 = cos(t3);
t5 = f.*2.0;
t6 = t-t5;
t10 = t2.*t6;
t7 = cos(-t10);
t8 = f.^2;
t9 = sin(t3);
ysol = -(t4.*y0-t7.*y0+t.*t4.*v0-t.*t7.*v0+t.*t2.*y0.*sin(-t10)-f.*t2.*t9.*y0.*2.0-k.*t4.*t8.*y0.*2.0-t2.*t8.*t9.*v0.*2.0+t.*t2.*t9.*y0+f.*k.*t.*t4.*y0.*2.0+f.*t.*t2.*t9.*v0.*2.0)./(cos(f.*t2.*2.0)+k.*t8.*2.0-1.0);
