function PSIk0 = TP2_PSIk0(t,f,y0,v0)
%TP2_PSIK0
%    PSIK0 = TP2_PSIK0(T,F,Y0,V0)

%    This function was generated by the Symbolic Math Toolbox version 8.1.
%    23-Jun-2018 13:23:20

PSIk0 = 1.0./f.^3.*(y0.^2.*3.0+f.^2.*v0.^2+f.*v0.*y0.*3.0).*4.0;
