function PSI = TP2_PSI(t,f,y0,v0,k)
%TP2_PSI
%    PSI = TP2_PSI(T,F,Y0,V0,K)

%    This function was generated by the Symbolic Math Toolbox version 7.2.
%    12-Jul-2017 23:54:00

t3 = sqrt(k);
t2 = sin(f.*t3);
t4 = v0.^2;
t5 = y0.^2;
t6 = f.*t3.*2.0;
t7 = sin(t6);
t8 = f.^2;
t9 = k.^2;
PSI = (f.*(k.*t4.*2.0+t5.*t9.*2.0)+k.^(3.0./2.0).*t5.*t7-t3.*t4.*t7+t8.*t9.*v0.*y0.*4.0)./(k.*t8-t2.^2)-k.*v0.*y0.*4.0;
