function uk0 = TP2_Uk0(t,f,y0,v0)
%TP2_UK0
%    UK0 = TP2_UK0(T,F,Y0,V0)

%    This function was generated by the Symbolic Math Toolbox version 8.1.
%    23-Jun-2018 13:23:19

uk0 = -1.0./f.^2.*(y0.*6.0+f.*v0.*4.0)+1.0./f.^3.*t.*(y0.*1.2e1+f.*v0.*6.0);
